import { Router } from 'express';
import { createGame } from '../routes/game/createGame.js';
import { getGame } from '../routes/game/getGame.js';
import { updateGame } from '../routes/game/updateGame.js';
import { deleteGame } from '../routes/game/deleteGame.js';
import { joinGame } from '../routes/game/joinGame.js';
import { getReady } from '../routes/game/getReady.js';
import { startGame } from '../routes/game/startGame.js';
import { leaveGame } from '../routes/game/leaveGame.js';
import { endGame } from '../routes/game/endGame.js';
import { getStatusGame } from '../routes/game/getStatusGame.js';
import { getPlayersInGame } from '../routes/game/getPlayersInGame.js';
import { getCurrentPlayer } from '../routes/game/getCurrentPlayer.js';
import { getTopCard } from '../routes/game/getTopCard.js';
import { getPlayerHands } from '../routes/game/getPlayerHands.js';
import { authMiddleware } from '../middleware/authenticate.js';
import { dealCards } from '../routes/game/dealCards.js';
import { sayUNO } from '../routes/game/sayUno.js';
import { challengePlayer } from '../routes/game/challengePlayer.js';
import { getGeneralStatus } from '../routes/game/getGeneralStatus.js';
import { getHistory } from '../routes/game/getHistory.js';
import { getPlayerHand } from '../routes/game/getPlayerHand.js';
import { checkHand } from '../routes/game/checkHand.js';
import { getAllGames } from '../routes/game/getAllGames.js';
const router = Router();

router.post('/games/', authMiddleware, createGame);
router.post('/games/:id', getGame);
router.get('/games/:id', getGame);
router.get('/games', getAllGames);
router.put('/games/:id', authMiddleware, updateGame);
router.delete('/games/:id', authMiddleware, deleteGame);
router.post('/game/join', authMiddleware, joinGame);
router.post('/game/ready', authMiddleware, getReady);
router.post('/game/start', authMiddleware, startGame);
router.post('/game/leave', authMiddleware, leaveGame);
router.post('/game/end', authMiddleware, endGame);
router.post('/game/dealCards/:id', authMiddleware, dealCards);
router.post('/game/uno', authMiddleware, sayUNO);
router.post('/game/challengeUno', authMiddleware, challengePlayer);

router.get('/game/status/', getStatusGame);
router.get('/game/players', getPlayersInGame);
router.get('/game/currentPlayer', getCurrentPlayer);
router.get('/game/topCard', getTopCard);
router.get('/game/playerHands', getPlayerHands);
router.get('/game/statusGeral', getGeneralStatus);
router.get('/game/history', getHistory);
router.get('/game/hand/', authMiddleware, getPlayerHand);
router.get('/game/checkHand/', authMiddleware, checkHand);

router.post('/game/status/', getStatusGame);
router.post('/game/players', getPlayersInGame);
router.post('/game/currentPlayer', getCurrentPlayer);
router.post('/game/topCard', getTopCard);
router.post('/game/playerHands', getPlayerHands);
router.post('/game/statusGeral', getGeneralStatus);
router.post('/game/history', getHistory);
router.post('/game/hand/', authMiddleware, getPlayerHand);
router.post('/game/checkHand/', authMiddleware, checkHand);

export default router;
